### ISSUE TITLE
How to handle updates

### ISSUE THREAD

**Issue by fasteddys** [RoverCore/RoverCore#13]
Hello if I use Rover in my project can you please share some guidance on how I can update `rover` and its `dependencies `in my project.

**Comment by tanczosm** [comment]
I'd call this alpha software at the moment.  Right now the project is being pretty regularly updated and we've been nailing down a lot of architectural decisions.  If you've installed the template you can just reinstall the template the same way and it will be updated with the newest dependencies and base code.  Or you can use the nuget package manager to grab the latest versions.

The last remaining big piece is the inclusion of some basic default email templates.  Everything else should be pretty stable at this point.

**Comment by fasteddys** [comment]
ok, so if I upgrade I wont loose my changes or is there a strategy like `modules`, or `partials `you recommend?
