### ISSUE TITLE
Features: Easy Material Theme support

### ISSUE THREAD

**Issue by fasteddys** [RoverCore/RoverCore#9]
Nice boiler plate, Can you add helpers for 

- [ ] #10
- [ ] 2. Theme support and localization

**Comment by tanczosm** [comment]
Thanks for the feedback.  I'll put that one out to the team.  We're still in pretty heavy development of this so this is not production-ready but we're trying to move pretty quickly (timeline of less than a month to finish).  We just finished inclusion of Visual Studio scaffolding mvc crud templates.  Part of the major lift for this project next is going to be documentation.

**Comment by tanczosm** [comment]
How did you find this boilerplate btw?

**Comment by papyr** [comment]
two ways, just google search for new templates, many show up, or can also look at product hunt. I also follow some Chinese developers who have a huge a good selection lot of pins. You can also get the word out on github page where they list all 4rd party tools for .NET

Going back to the suggestions, there are many but with _older poorer structure_ no patterns, and incompatible or don't take advantage of boilerplate patterns. 

The rest, are just ABP/ASPnetZero/Orchard/Serinity etc are `un-affordable` or too Complex for a one or two developers that are building small quick sites for e.g. a non profit, day care, photographers or basic sites that need some reliable and secure transactions.

I was using scaffolding for sometime, but then when you have to go back and update a model or re-scaffold its a nightmare. I now prefer patterns, repository, UOW, audits, breadcrumbs, claims, helpers, utils, 

The best is if you can `combine patterns with scaffolder's` - _which is ABP's secret sauce!_ look at EASY ABPGUI its open source.. hope this helps.

**Comment by tanczosm** [comment]
Right now our objective is to find that sweet spot where we aren't too complex but are also well-documented like abp, orchard, etc.   We're skipping all the skinny-controller, repository, cqrs, mediatr, etc. stuff and keeping it simple where possible.

Ultimately we want to have something more beginner friendly, so we're going to probably but as much work into documentation as the theme itself.  

I'd like to be able to make it possible to have modular areas but I haven't quite been able to figure out how to solve that one.

**Comment by fasteddys** [comment]
Thats going to be a hard balance, 

- [ ] Please don't totally ignore the patterns, aggregates and repos. IMHO - let developers add those services as an option/configuration
- [ ] Rapid App Dev, `is the key here` with good quality fro LOB transactional systems, with Users/Roles/Claims UI baked in. 
Check out Tuxboard on github it might give you a good start on the dashboards I was trying to encourage his development.
